AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Athena Table Creator Lambda'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, acceptance, prod]
    Description: Environment name for resource tagging

  CodeBucket:
    Type: String
    Description: S3 bucket containing the code for Lambda

  CodePrefix:
    Type: String
    Description: S3 path within bucket containing the zip file for Lambda 
  
  DataBucket:
    Type: String
    Description: S3 bucket containing the data for Athena tables

  LambdaIAMRoleARN:
    Type: String
    Description: IAM role ARN for Lambda
  
  DatabaseName:
    Type: String
    Description: Athena/Glue database name

Resources:

  AthenaTableCreatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaIAMRoleARN
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodePrefix
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DATA_BUCKET: !Ref DataBucket
          DATABASE_NAME: !Ref DatabaseName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: AthenaTableCreator

Outputs:
  LambdaArn:
    Description: ARN of the created Lambda function
    Value: !GetAtt AthenaTableCreatorLambda.Arn
