AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Athena Table Creator Lambda'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name for resource tagging
  
  DataBucket:
    Type: String
    Description: S3 bucket containing the data for Athena tables
    Default: athena-spark-datastore

  CodeBucket:
    Type: String
    Description: S3 bucket containing the code for Lambda
    Default: athena-spark-datastore
  
  DatabaseName:
    Type: String
    Description: Athena/Glue database name
    Default: default

Resources:

  AthenaTableCreatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: athena-table-creator.lambda_handler
      Role: !GetAtt AthenaTableCreatorRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: athena-table-creator.zip
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          RESULTS_BUCKET: !Ref ResultsBucket
          DATA_BUCKET: !Ref DataBucket
          DATABASE_NAME: !Ref DatabaseName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: AthenaTableCreator

Outputs:
  LambdaArn:
    Description: ARN of the created Lambda function
    Value: !GetAtt AthenaTableCreatorLambda.Arn
